version = 0.1

[default.global.parameters]
region = "eu-central-1"
s3_bucket = "kinesis-bucket-test"
s3_prefix = "kinesis-stream"
[default.deploy.parameters]
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
stack_name = "kinesis-stream"
tags = "project=\"kinesis\" env=\"test\" customer=\"internal\" cost-allocation=\"kinesis-test\""

[dev.global.parameters]
region = "eu-central-1"
s3_bucket = "kinesis-bucket-test"
s3_prefix = "kinesis-stream"
[dev.deploy.parameters]
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
stack_name = "kinesis-stream"
tags = "project=\"kinesis\" env=\"test\" customer=\"internal\" cost-allocation=\"kinesis-test\""


